[package]
name = "hdsleep"
version = "0.2.1"
edition = "2021"
rust-version = "1.78.0"

[[bin]]
name = "hdsleep"
path = "hdsleep.rs"

[profile.release]
opt-level = "z"
lto = "fat"
strip = true
codegen-units = 1
panic = "abort"

[dependencies]
libc = "0.2.169"
